// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"context"
	commonModel "github.com/kennylixi/gadmin/internal/modules/common/model"
	systemModel "github.com/kennylixi/gadmin/internal/modules/system/model"
	"github.com/kennylixi/gadmin/internal/modules/system/model/entity"
)

type (
	IApi interface {
		SelectById(ctx context.Context, apiId int64) (ent *entity.Api, err error)
		SelectByIds(ctx context.Context, apiIds []int64) (list []*entity.Api, err error)
		SelectList(ctx context.Context, in *systemModel.ApiListInput) (out *systemModel.ApiListOutput, err error)
		SelectModuleList(ctx context.Context) (out []string, err error)
		SelectApisByRoleId(ctx context.Context, roleId int64) (apiIds []int64, err error)
		Treeselect(ctx context.Context) (items []*commonModel.TreeSelect, err error)
		SelectApiListByMenuIds(ctx context.Context, menuIds []int64) (apis []*entity.Api, err error)
		Insert(ctx context.Context, in *systemModel.ApiAddInput) (err error)
		Update(ctx context.Context, in *systemModel.ApiEditInput) (err error)
		DeleteByIds(ctx context.Context, apiIds []int64) (err error)
		ReImportAll(ctx context.Context) (err error)
	}
)

var (
	localApi IApi
)

func Api() IApi {
	if localApi == nil {
		panic("implement not found for interface IApi, forgot register?")
	}
	return localApi
}

func RegisterApi(i IApi) {
	localApi = i
}
