// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"context"
	"github.com/kennylixi/gadmin/internal/modules/system/model"
	"github.com/kennylixi/gadmin/internal/modules/system/model/entity"
)

type (
	IDictType interface {
		List(ctx context.Context, in *model.DictTypeListInput) (out *model.DictTypeListOutput, err error)
		SelectDictTypeAll(ctx context.Context) (list []*entity.DictType, err error)
		GetInfo(ctx context.Context, dictId int64) (dictType *entity.DictType, err error)
		Add(ctx context.Context, in *model.DictTypeAddInput) error
		Edit(ctx context.Context, in *model.DictTypeEditInput) error
		Delete(ctx context.Context, dictIds []int64) error
		CheckDictTypeUnique(ctx context.Context, dictType string, dictId int64) (bool, error)
	}
)

var (
	localDictType IDictType
)

func DictType() IDictType {
	if localDictType == nil {
		panic("implement not found for interface IDictType, forgot register?")
	}
	return localDictType
}

func RegisterDictType(i IDictType) {
	localDictType = i
}
