// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"context"
	"github.com/kennylixi/gadmin/internal/modules/system/model/entity"
)

type (
	IDictCache interface {
		LoadingDictCache(ctx context.Context) error
		ClearCache(ctx context.Context) error
		ResetCache(ctx context.Context) error
		GetCacheKey(ctx context.Context, dictType string) string
		DelCache(ctx context.Context, dictType string) error
		SetCache(ctx context.Context, dictType string, dictDatas []*entity.DictData) error
		GetCache(ctx context.Context, dictType string) (dictDatas []*entity.DictData)
		GetDictLabel(ctx context.Context, dictType, dictValue, separator string) string
		GetDictValue(ctx context.Context, dictType, dictLabel, separator string) string
	}
)

var (
	localDictCache IDictCache
)

func DictCache() IDictCache {
	if localDictCache == nil {
		panic("implement not found for interface IDictCache, forgot register?")
	}
	return localDictCache
}

func RegisterDictCache(i IDictCache) {
	localDictCache = i
}
