// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"context"
	"github.com/kennylixi/gadmin/internal/modules/system/model/entity"
)

type (
	IGenTableColumn interface {
		SelectGenTableColumnListByTableId(ctx context.Context, tableId int64) ([]*entity.GenTableColumn, error)
		InsertGenTableColumn(ctx context.Context, genTableColumn *entity.GenTableColumn) (int64, error)
		UpdateGenTableColumn(ctx context.Context, genTableColumn *entity.GenTableColumn) (int64, error)
		DeleteGenTableColumnByIds(ctx context.Context, ids []int64) (int64, error)
	}
)

var (
	localGenTableColumn IGenTableColumn
)

func GenTableColumn() IGenTableColumn {
	if localGenTableColumn == nil {
		panic("implement not found for interface IGenTableColumn, forgot register?")
	}
	return localGenTableColumn
}

func RegisterGenTableColumn(i IGenTableColumn) {
	localGenTableColumn = i
}
