// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"context"
	"github.com/kennylixi/gadmin/internal/modules/system/model"
	"github.com/kennylixi/gadmin/internal/modules/system/model/do"
	"github.com/kennylixi/gadmin/internal/modules/system/model/entity"
)

type (
	IJobLog interface {
		SelectJobLogById(ctx context.Context, jobLogId int64) (*entity.JobLog, error)
		SelectJobLogList(ctx context.Context, in *model.JobLogListInput) (out *model.JobLogListOutput, err error)
		BatchInsert(ctx context.Context, count int64) error
		UpdateJobLog(ctx context.Context, jobLog *do.JobLog) error
		DeleteJobLogByIds(ctx context.Context, jobLogIds []int64) error
		Clean(ctx context.Context) error
	}
)

var (
	localJobLog IJobLog
)

func JobLog() IJobLog {
	if localJobLog == nil {
		panic("implement not found for interface IJobLog, forgot register?")
	}
	return localJobLog
}

func RegisterJobLog(i IJobLog) {
	localJobLog = i
}
