// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"context"
	commonModel "github.com/kennylixi/gadmin/internal/modules/common/model"
	systemModel "github.com/kennylixi/gadmin/internal/modules/system/model"
)

type (
	IMenu interface {
		SelectMenuList(ctx context.Context, in *systemModel.MenuSelectListInput) ([]*systemModel.Menu, error)
		SelectMenuTreeByUserId(ctx context.Context, userId int64) ([]*systemModel.Menu, error)
		SelectMenuById(ctx context.Context, menuId int64) (*systemModel.Menu, error)
		SelectMenuPermsByUserId(ctx context.Context, userId int64) ([]string, error)
		SelectMenuListByRoleId(ctx context.Context, roleId int64) ([]int64, error)
		BuildMenuTreeSelect(menus []*systemModel.Menu) []*commonModel.TreeSelect
		BuildMenus(menus []*systemModel.Menu) []*systemModel.RouterVo
		Add(ctx context.Context, in *systemModel.MenuAddInput) (err error)
		Edit(ctx context.Context, in *systemModel.MenuEditInput) (err error)
		Delete(ctx context.Context, menuId int64) (err error)
	}
)

var (
	localMenu IMenu
)

func Menu() IMenu {
	if localMenu == nil {
		panic("implement not found for interface IMenu, forgot register?")
	}
	return localMenu
}

func RegisterMenu(i IMenu) {
	localMenu = i
}
