// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"context"
	"github.com/kennylixi/gadmin/internal/modules/system/model"
	"github.com/kennylixi/gadmin/internal/modules/system/model/entity"
)

type (
	INotice interface {
		SelectNoticeById(ctx context.Context, noticeId int64) (*entity.Notice, error)
		SelectNoticeList(ctx context.Context, in *model.NoticeListInput) (out *model.NoticeListOutput, err error)
		Add(ctx context.Context, in *model.NoticeAddInput) error
		Edit(ctx context.Context, in *model.NoticeEditInput) error
		Delete(ctx context.Context, noticeIds []int64) error
	}
)

var (
	localNotice INotice
)

func Notice() INotice {
	if localNotice == nil {
		panic("implement not found for interface INotice, forgot register?")
	}
	return localNotice
}

func RegisterNotice(i INotice) {
	localNotice = i
}
