// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"context"
	"github.com/kennylixi/gadmin/internal/modules/system/model"
	"github.com/kennylixi/gadmin/internal/modules/system/model/entity"
)

type (
	IOperLog interface {
		BatchInsert(ctx context.Context, count int64) error
		SelectList(ctx context.Context, in *model.OperLogListInput) (out *model.OperLogListOutput, err error)
		DeleteByIds(ctx context.Context, operIds []int64) error
		SelectById(ctx context.Context, operId int64) (*entity.OperLog, error)
		Clean(ctx context.Context) error
	}
)

var (
	localOperLog IOperLog
)

func OperLog() IOperLog {
	if localOperLog == nil {
		panic("implement not found for interface IOperLog, forgot register?")
	}
	return localOperLog
}

func RegisterOperLog(i IOperLog) {
	localOperLog = i
}
