// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"context"
	"github.com/kennylixi/gadmin/internal/modules/system/model"
	"github.com/kennylixi/gadmin/internal/modules/system/model/entity"
)

type (
	IPost interface {
		SelectPostById(ctx context.Context, postId int64) (*entity.Post, error)
		SelectPostList(ctx context.Context, in *model.PostListInput) (out *model.PostListOutput, err error)
		SelectPostAll(ctx context.Context) ([]*entity.Post, error)
		SelectPostListByUserId(ctx context.Context, userId int64) ([]int64, error)
		SelectPostsByUserName(ctx context.Context, userName string) ([]*entity.Post, error)
		GetByPostName(ctx context.Context, postName string) (*entity.Post, error)
		GetByPostCode(ctx context.Context, postCode string) (*entity.Post, error)
		Add(ctx context.Context, in *model.PostAddInput) error
		Edit(ctx context.Context, in *model.PostEditInput) error
		Delete(ctx context.Context, postIds []int64) error
	}
)

var (
	localPost IPost
)

func Post() IPost {
	if localPost == nil {
		panic("implement not found for interface IPost, forgot register?")
	}
	return localPost
}

func RegisterPost(i IPost) {
	localPost = i
}
