// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"context"
	"github.com/kennylixi/gadmin/internal/modules/system/model"
	"github.com/kennylixi/gadmin/internal/modules/system/model/entity"
)

type (
	IPushTemplate interface {
		SelectById(ctx context.Context, id int64) (pushTempate *entity.PushTemplate, err error)
		SelectByCode(ctx context.Context, code string) (pushTempate *entity.PushTemplate, err error)
		SelectList(ctx context.Context, in *model.PushTemplateListInput) (out *model.PushTemplateListOutput, err error)
		Insert(ctx context.Context, in *model.PushTemplateAddInput) (err error)
		Update(ctx context.Context, in *model.PushTemplateEditInput) (err error)
		HasByChannelIds(ctx context.Context, channelIds ...int64) (has bool, err error)
		DeleteByIds(ctx context.Context, ids []int64) (err error)
		SendTest(ctx context.Context, in *model.PushTemplateTestInput) (err error)
	}
)

var (
	localPushTemplate IPushTemplate
)

func PushTemplate() IPushTemplate {
	if localPushTemplate == nil {
		panic("implement not found for interface IPushTemplate, forgot register?")
	}
	return localPushTemplate
}

func RegisterPushTemplate(i IPushTemplate) {
	localPushTemplate = i
}
