// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"context"
	"github.com/kennylixi/gadmin/internal/modules/system/model"
	"github.com/kennylixi/gadmin/internal/modules/system/model/entity"
)

type (
	IRole interface {
		SelectRoleList(ctx context.Context, in *model.RoleListInput) (out *model.RoleListOutput, err error)
		SelectRolesByUserId(ctx context.Context, userId int64) (roles []*model.Role, err error)
		SelectAllRolesByUserId(ctx context.Context, userId int64) (roles []*model.Role, err error)
		SelectRolePermissionByUserId(ctx context.Context, userId int64) ([]string, error)
		SelectRoleAll(ctx context.Context) ([]*model.Role, error)
		SelectRoleListByUserId(ctx context.Context, userId int64) ([]int64, error)
		SelectRoleKeyByMenuIds(ctx context.Context, menuIds []int64) (roleKeys []string, err error)
		SelectRoleById(ctx context.Context, roleId int64) (*entity.Role, error)
		SelectRolesByIds(ctx context.Context, roleIds []int64) (roles []*entity.Role, err error)
		CheckRoleNameUnique(ctx context.Context, roleName string, roleId ...int64) (bool, error)
		CheckRoleKeyUnique(ctx context.Context, roleKey string, roleId ...int64) (bool, error)
		CheckRoleAllowed(roleId int64) error
		Add(ctx context.Context, in *model.RoleAddInput) error
		Edit(ctx context.Context, in *model.RoleEditInput) error
		UpdateRoleStatus(ctx context.Context, roleId int64, status string) (err error)
		AuthDataScope(ctx context.Context, roleId int64, deptIds []int64, dataScope int) error
		DeleteByIds(ctx context.Context, roleIds []int64) (err error)
		DeleteAuthUser(ctx context.Context, roleId int64, userId int64) (err error)
		DeleteAuthUsers(ctx context.Context, roleId int64, userIds []int64) (err error)
		InsertAuthUsers(ctx context.Context, roleId int64, userIds []int64) (err error)
	}
)

var (
	localRole IRole
)

func Role() IRole {
	if localRole == nil {
		panic("implement not found for interface IRole, forgot register?")
	}
	return localRole
}

func RegisterRole(i IRole) {
	localRole = i
}
