// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"context"
	"github.com/kennylixi/gadmin/internal/modules/system/model"
	"github.com/kennylixi/gadmin/internal/modules/system/model/entity"
)

type (
	ISqlBackups interface {
		SelectById(ctx context.Context, backupsId int64) (sysSqlBackups *entity.SqlBackups, err error)
		SelectList(ctx context.Context, in *model.SqlBackupsListInput) (out *model.SqlBackupsListOutput, err error)
		Backup(ctx context.Context) (err error)
		Recover(ctx context.Context, backupsId int64) (err error)
		DeleteByIds(ctx context.Context, backupsIds []int64) (err error)
	}
)

var (
	localSqlBackups ISqlBackups
)

func SqlBackups() ISqlBackups {
	if localSqlBackups == nil {
		panic("implement not found for interface ISqlBackups, forgot register?")
	}
	return localSqlBackups
}

func RegisterSqlBackups(i ISqlBackups) {
	localSqlBackups = i
}
