// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"context"
	"github.com/kennylixi/gadmin/internal/modules/system/model"

	"github.com/goflyfox/gtoken/gtoken"
	"github.com/gogf/gf/v2/net/ghttp"
)

type (
	IToken interface {
		Init(ctx context.Context) error
		AdminMiddleware(ctx context.Context, group *ghttp.RouterGroup)
		LoginAfter(r *ghttp.Request, respData gtoken.Resp)
		AuthAfterFunc(r *ghttp.Request, respData gtoken.Resp)
		GetLoginUser(r *ghttp.Request) (userInfo *model.User)
		LoginOut(r *ghttp.Request) bool
		RemoveToken(ctx context.Context, token string) gtoken.Resp
		Login(r *ghttp.Request) (string, interface{})
	}
)

var (
	localToken IToken
)

func Token() IToken {
	if localToken == nil {
		panic("implement not found for interface IToken, forgot register?")
	}
	return localToken
}

func RegisterToken(i IToken) {
	localToken = i
}
