// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"context"
	"github.com/kennylixi/gadmin/internal/modules/system/model"
	"github.com/kennylixi/gadmin/internal/modules/system/model/do"
)

type (
	IUserOnline interface {
		SelectList(ctx context.Context, in *model.UserOnlineListInput) (out *model.UserOnlineListOutput, err error)
		ForceLogout(ctx context.Context, tokenId string) error
		DeleteByToken(ctx context.Context, token string) error
		Save(ctx context.Context, online *do.UserOnline) error
	}
)

var (
	localUserOnline IUserOnline
)

func UserOnline() IUserOnline {
	if localUserOnline == nil {
		panic("implement not found for interface IUserOnline, forgot register?")
	}
	return localUserOnline
}

func RegisterUserOnline(i IUserOnline) {
	localUserOnline = i
}
