// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// PushTemplateDao is the data access object for table sys_push_template.
type PushTemplateDao struct {
	table   string              // table is the underlying table name of the DAO.
	group   string              // group is the database configuration group name of current DAO.
	columns PushTemplateColumns // columns contains all the column names of Table for convenient usage.
}

// PushTemplateColumns defines and stores column names for table sys_push_template.
type PushTemplateColumns struct {
	Id        string // 编号
	Name      string // 模板名称
	Code      string // 模板编码
	ChannelId string // 渠道ID
	Params    string // 渠道信息
	Status    string // 状态（0开启 1禁用）
	Cron      string // 执行时间(0实时，定时cron表达式)
	MsgType   string // 消息类型
	Remark    string // 备注
	CreateBy  string // 创建者
	CreatedAt string // 创建时间
	UpdateBy  string // 更新者
	UpdatedAt string // 更新时间
}

// pushTemplateColumns holds the columns for table sys_push_template.
var pushTemplateColumns = PushTemplateColumns{
	Id:        "id",
	Name:      "name",
	Code:      "code",
	ChannelId: "channel_id",
	Params:    "params",
	Status:    "status",
	Cron:      "cron",
	MsgType:   "msg_type",
	Remark:    "remark",
	CreateBy:  "create_by",
	CreatedAt: "created_at",
	UpdateBy:  "update_by",
	UpdatedAt: "updated_at",
}

// NewPushTemplateDao creates and returns a new DAO object for table data access.
func NewPushTemplateDao() *PushTemplateDao {
	return &PushTemplateDao{
		group:   "default",
		table:   "sys_push_template",
		columns: pushTemplateColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *PushTemplateDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *PushTemplateDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *PushTemplateDao) Columns() PushTemplateColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *PushTemplateDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *PushTemplateDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *PushTemplateDao) Transaction(ctx context.Context, f func(ctx context.Context, tx gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
