// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// PushChannelDao is the data access object for table sys_push_channel.
type PushChannelDao struct {
	table   string             // table is the underlying table name of the DAO.
	group   string             // group is the database configuration group name of current DAO.
	columns PushChannelColumns // columns contains all the column names of Table for convenient usage.
}

// PushChannelColumns defines and stores column names for table sys_push_channel.
type PushChannelColumns struct {
	Id        string // 编号
	Name      string // 渠道名称
	TypeId    string // 渠道类型
	Remark    string // 备注
	Status    string // 状态（0开启 1禁用）
	Config    string // 渠道配置
	CreateBy  string // 创建者
	CreatedAt string // 创建时间
	UpdateBy  string // 更新者
	UpdatedAt string // 更新时间
}

// pushChannelColumns holds the columns for table sys_push_channel.
var pushChannelColumns = PushChannelColumns{
	Id:        "id",
	Name:      "name",
	TypeId:    "type_id",
	Remark:    "remark",
	Status:    "status",
	Config:    "config",
	CreateBy:  "create_by",
	CreatedAt: "created_at",
	UpdateBy:  "update_by",
	UpdatedAt: "updated_at",
}

// NewPushChannelDao creates and returns a new DAO object for table data access.
func NewPushChannelDao() *PushChannelDao {
	return &PushChannelDao{
		group:   "default",
		table:   "sys_push_channel",
		columns: pushChannelColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *PushChannelDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *PushChannelDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *PushChannelDao) Columns() PushChannelColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *PushChannelDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *PushChannelDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *PushChannelDao) Transaction(ctx context.Context, f func(ctx context.Context, tx gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
