// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// RoleDao is the data access object for table sys_role.
type RoleDao struct {
	table   string      // table is the underlying table name of the DAO.
	group   string      // group is the database configuration group name of current DAO.
	columns RoleColumns // columns contains all the column names of Table for convenient usage.
}

// RoleColumns defines and stores column names for table sys_role.
type RoleColumns struct {
	RoleId            string // 角色ID
	RoleName          string // 角色名称
	RoleKey           string // 角色权限字符串
	RoleSort          string // 显示顺序
	DataScope         string // 数据范围（1：全部数据权限 2：自定数据权限 3：本部门数据权限 4：本部门及以下数据权限）
	MenuCheckStrictly string // 菜单树选择项是否关联显示
	ApiCheckStrictly  string // 接口树选择项是否关联显示
	DeptCheckStrictly string // 部门树选择项是否关联显示（0：父子不互相关联显示 1：父子互相关联显示 ）
	Status            string // 角色状态（0正常 1停用）
	CreateBy          string // 创建者
	CreatedAt         string // 创建时间
	UpdateBy          string // 更新者
	UpdatedAt         string // 更新时间
	DeletedAt         string // 删除标识
	Remark            string // 备注
}

// roleColumns holds the columns for table sys_role.
var roleColumns = RoleColumns{
	RoleId:            "role_id",
	RoleName:          "role_name",
	RoleKey:           "role_key",
	RoleSort:          "role_sort",
	DataScope:         "data_scope",
	MenuCheckStrictly: "menu_check_strictly",
	ApiCheckStrictly:  "api_check_strictly",
	DeptCheckStrictly: "dept_check_strictly",
	Status:            "status",
	CreateBy:          "create_by",
	CreatedAt:         "created_at",
	UpdateBy:          "update_by",
	UpdatedAt:         "updated_at",
	DeletedAt:         "deleted_at",
	Remark:            "remark",
}

// NewRoleDao creates and returns a new DAO object for table data access.
func NewRoleDao() *RoleDao {
	return &RoleDao{
		group:   "default",
		table:   "sys_role",
		columns: roleColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *RoleDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *RoleDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *RoleDao) Columns() RoleColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *RoleDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *RoleDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *RoleDao) Transaction(ctx context.Context, f func(ctx context.Context, tx gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
