// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// SqlBackupsDao is the data access object for table sys_sql_backups.
type SqlBackupsDao struct {
	table   string            // table is the underlying table name of the DAO.
	group   string            // group is the database configuration group name of current DAO.
	columns SqlBackupsColumns // columns contains all the column names of Table for convenient usage.
}

// SqlBackupsColumns defines and stores column names for table sys_sql_backups.
type SqlBackupsColumns struct {
	BackupsId string // 备份ID
	FileName  string // 文件名称
	Password  string // 加密密码
	FileSize  string // 文件大小
	CreatedAt string // 备份时间
}

// sqlBackupsColumns holds the columns for table sys_sql_backups.
var sqlBackupsColumns = SqlBackupsColumns{
	BackupsId: "backups_id",
	FileName:  "file_name",
	Password:  "password",
	FileSize:  "file_size",
	CreatedAt: "created_at",
}

// NewSqlBackupsDao creates and returns a new DAO object for table data access.
func NewSqlBackupsDao() *SqlBackupsDao {
	return &SqlBackupsDao{
		group:   "default",
		table:   "sys_sql_backups",
		columns: sqlBackupsColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *SqlBackupsDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *SqlBackupsDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *SqlBackupsDao) Columns() SqlBackupsColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *SqlBackupsDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *SqlBackupsDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *SqlBackupsDao) Transaction(ctx context.Context, f func(ctx context.Context, tx gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
