// ============================================================================
// This is auto-generated by gen tool only once. Fill this file as you wish.
// 文件管理Controller层
// @author kennylixi
// @date 2023-03-23 14:14:45
// ============================================================================

package admin

import (
	"context"
	"github.com/kennylixi/gadmin/internal/modules/system/api/v1/admin"
	"github.com/kennylixi/gadmin/internal/modules/system/model"
	sysService "github.com/kennylixi/gadmin/internal/modules/system/service"
)

// File 文件管理管理
var File = cFile{}

type cFile struct{}

// List 查询文件管理列表
func (c *cFile) List(ctx context.Context, req *admin.FileListReq) (res *admin.FileListRes, err error) {
	out, err := sysService.File().SelectList(ctx, &model.FileListInput{
		Key: req.Key,
	})
	if err != nil {
		return
	}
	res = &admin.FileListRes{
		List:  out.List,
		Total: out.Total,
	}
	return
}

// GetInfo 获取文件管理详细信息
func (c *cFile) GetInfo(ctx context.Context, req *admin.FileGetInfoReq) (res *admin.FileGetInfoRes, err error) {
	out, err := sysService.File().SelectById(ctx, req.Id)
	if err != nil {
		return
	}
	res = (*admin.FileGetInfoRes)(out)
	return
}

// Delete 删除文件管理
func (c *cFile) Delete(ctx context.Context, req *admin.FileDeleteReq) (res *admin.FileDeleteRes, err error) {
	err = sysService.File().DeleteByIds(ctx, req.Ids)
	return
}
