// ============================================================================
// This is auto-generated by gen tool only once. Fill this file as you wish.
// 驱动配置Controller层
// @author kennylixi
// @date 2023-03-23 14:15:08
// ============================================================================

package admin

import (
	"context"
	commonService "github.com/kennylixi/gadmin/internal/modules/common/service"
	"github.com/kennylixi/gadmin/internal/modules/system/api/v1/admin"
	"github.com/kennylixi/gadmin/internal/modules/system/model"
	sysService "github.com/kennylixi/gadmin/internal/modules/system/service"
)

// FileDriver 驱动配置管理
var FileDriver = cFileDriver{}

type cFileDriver struct{}

// List 查询驱动配置列表
func (c *cFileDriver) List(ctx context.Context, req *admin.FileDriverListReq) (res *admin.FileDriverListRes, err error) {
	out, err := sysService.FileDriver().SelectList(ctx, &model.FileDriverListInput{
		Name:   req.Name,
		Driver: req.Driver,
	})
	if err != nil {
		return
	}
	res = &admin.FileDriverListRes{
		List:  out.List,
		Total: out.Total,
	}
	return
}

// GetInfo 获取驱动配置详细信息
func (c *cFileDriver) GetInfo(ctx context.Context, req *admin.FileDriverGetInfoReq) (res *admin.FileDriverGetInfoRes, err error) {
	out, err := sysService.FileDriver().SelectById(ctx, req.Id)
	if err != nil {
		return
	}
	res = (*admin.FileDriverGetInfoRes)(out)
	return
}

// Add 新增驱动配置
func (c *cFileDriver) Add(ctx context.Context, req *admin.FileDriverAddReq) (res *admin.FileDriverAddRes, err error) {
	in := &model.FileDriverAddInput{
		Name:     req.Name,
		Driver:   req.Driver,
		Remark:   req.Remark,
		Master:   req.Master,
		Config:   req.Config,
		CreateBy: commonService.BizCtx().GetUserName(ctx),
	}
	err = sysService.FileDriver().Insert(ctx, in)
	return
}

// Edit 修改驱动配置
func (c *cFileDriver) Edit(ctx context.Context, req *admin.FileDriverEditReq) (res *admin.FileDriverEditRes, err error) {
	in := &model.FileDriverEditInput{
		Id:       req.Id,
		Name:     req.Name,
		Driver:   req.Driver,
		Remark:   req.Remark,
		Master:   req.Master,
		Config:   req.Config,
		UpdateBy: commonService.BizCtx().GetUserName(ctx),
	}
	err = sysService.FileDriver().Update(ctx, in)
	return
}

// Delete 删除驱动配置
func (c *cFileDriver) Delete(ctx context.Context, req *admin.FileDriverDeleteReq) (res *admin.FileDriverDeleteRes, err error) {
	err = sysService.FileDriver().DeleteByIds(ctx, req.Ids)
	return
}

// Master 设置主驱动配置
func (c *cFileDriver) Master(ctx context.Context, req *admin.FileDriverMasterReq) (res *admin.FileDriverMasterRes, err error) {
	err = sysService.FileDriver().SetMaster(ctx, req.Id)
	return
}

// Test 测试驱动配置
func (c *cFileDriver) Test(ctx context.Context, req *admin.FileDriverTestReq) (res *admin.FileDriverTestRes, err error) {
	err = sysService.FileDriver().Test(ctx, req.Id)
	return
}
