// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package logic

import (
	_ "github.com/kennylixi/gadmin/internal/modules/system/logic/api"
	_ "github.com/kennylixi/gadmin/internal/modules/system/logic/casbin"
	_ "github.com/kennylixi/gadmin/internal/modules/system/logic/config"
	_ "github.com/kennylixi/gadmin/internal/modules/system/logic/dept"
	_ "github.com/kennylixi/gadmin/internal/modules/system/logic/dict_cache"
	_ "github.com/kennylixi/gadmin/internal/modules/system/logic/dict_data"
	_ "github.com/kennylixi/gadmin/internal/modules/system/logic/dict_type"
	_ "github.com/kennylixi/gadmin/internal/modules/system/logic/district"
	_ "github.com/kennylixi/gadmin/internal/modules/system/logic/file"
	_ "github.com/kennylixi/gadmin/internal/modules/system/logic/file_driver"
	_ "github.com/kennylixi/gadmin/internal/modules/system/logic/gen_table"
	_ "github.com/kennylixi/gadmin/internal/modules/system/logic/gen_table_column"
	_ "github.com/kennylixi/gadmin/internal/modules/system/logic/hook"
	_ "github.com/kennylixi/gadmin/internal/modules/system/logic/job"
	_ "github.com/kennylixi/gadmin/internal/modules/system/logic/job_log"
	_ "github.com/kennylixi/gadmin/internal/modules/system/logic/logininfor"
	_ "github.com/kennylixi/gadmin/internal/modules/system/logic/menu"
	_ "github.com/kennylixi/gadmin/internal/modules/system/logic/notice"
	_ "github.com/kennylixi/gadmin/internal/modules/system/logic/oper_log"
	_ "github.com/kennylixi/gadmin/internal/modules/system/logic/permission"
	_ "github.com/kennylixi/gadmin/internal/modules/system/logic/post"
	_ "github.com/kennylixi/gadmin/internal/modules/system/logic/push_channel"
	_ "github.com/kennylixi/gadmin/internal/modules/system/logic/push_template"
	_ "github.com/kennylixi/gadmin/internal/modules/system/logic/push_type"
	_ "github.com/kennylixi/gadmin/internal/modules/system/logic/role"
	_ "github.com/kennylixi/gadmin/internal/modules/system/logic/sql_backups"
	_ "github.com/kennylixi/gadmin/internal/modules/system/logic/token"
	_ "github.com/kennylixi/gadmin/internal/modules/system/logic/user"
	_ "github.com/kennylixi/gadmin/internal/modules/system/logic/user_online"
)
