// ============================================================================
// This is auto-generated by gen tool only once. Fill this file as you wish.
// 接口管理Dao
// @author kennylixi
// @date 2023-05-14 11:01:08
// ============================================================================

package dao

import "github.com/kennylixi/gadmin/internal/modules/system/dao/internal"

// internalApiDao is internal type for wrapping internal DAO implements.
type internalApiDao = *internal.ApiDao

// apiDao is the data access object for table sys_api.
// You can define custom methods on it to extend its functionality as you wish.
type apiDao struct {
	internalApiDao
}

var (
	// Api is globally public accessible object for table sys_api operations.
	Api = apiDao{
		internal.NewApiDao(),
	}
)

// Fill with you ideas below.
