// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"context"
	"github.com/kennylixi/gadmin/internal/modules/system/dao/internal"
	"github.com/kennylixi/gadmin/internal/modules/system/model/entity"
)

// internalDictTypeDao is internal type for wrapping internal DAO implements.
type internalDictTypeDao = *internal.DictTypeDao

// dictTypeDao is the data access object for table sys_dict_type.
// You can define custom methods on it to extend its functionality as you wish.
type dictTypeDao struct {
	internalDictTypeDao
}

var (
	// DictType is globally public accessible object for table sys_dict_type operations.
	DictType = dictTypeDao{
		internal.NewDictTypeDao(),
	}
)

// Fill with you ideas below.

// GetByDictType 根据字典类型名获取字典类型数据
//	@param dictType 字典类型名
//	@return 字典类型
func (d *dictTypeDao) GetByDictType(ctx context.Context, dictType string) (result *entity.DictType, err error) {
	err = d.Ctx(ctx).Where(DictType.Columns().DictType, dictType).Scan(&result)
	if err != nil {
		return nil, err
	}
	return result, nil
}
