// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/kennylixi/gadmin/internal/modules/system/dao/internal"
)

// internalFileDriverDao is internal type for wrapping internal DAO implements.
type internalFileDriverDao = *internal.FileDriverDao

// fileDriverDao is the data access object for table sys_file_driver.
// You can define custom methods on it to extend its functionality as you wish.
type fileDriverDao struct {
	internalFileDriverDao
}

var (
	// FileDriver is globally public accessible object for table sys_file_driver operations.
	FileDriver = fileDriverDao{
		internal.NewFileDriverDao(),
	}
)

// Fill with you ideas below.
