// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/kennylixi/gadmin/internal/modules/system/dao/internal"
)

// internalPushTypeDao is internal type for wrapping internal DAO implements.
type internalPushTypeDao = *internal.PushTypeDao

// pushTypeDao is the data access object for table sys_push_type.
// You can define custom methods on it to extend its functionality as you wish.
type pushTypeDao struct {
	internalPushTypeDao
}

var (
	// PushType is globally public accessible object for table sys_push_type operations.
	PushType = pushTypeDao{
		internal.NewPushTypeDao(),
	}
)

// Fill with you ideas below.
