// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"context"
	"github.com/kennylixi/gadmin/internal/modules/system/dao/internal"
)

// internalRoleMenuDao is internal type for wrapping internal DAO implements.
type internalRoleMenuDao = *internal.RoleMenuDao

// roleMenuDao is the data access object for table sys_role_menu.
// You can define custom methods on it to extend its functionality as you wish.
type roleMenuDao struct {
	internalRoleMenuDao
}

var (
	// RoleMenu is globally public accessible object for table sys_role_menu operations.
	RoleMenu = roleMenuDao{
		internal.NewRoleMenuDao(),
	}
)

// Fill with you ideas below.

// CheckMenuExistRole 查询菜单使用数量
// @param menuId 菜单ID
// @return 结果
func (d *roleMenuDao) CheckMenuExistRole(ctx context.Context, menuId int64) int {
	count, err := RoleMenu.Ctx(ctx).Count(RoleMenu.Columns().MenuId, menuId)
	if err != nil {
		panic(err)
	}
	return count
}
