// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/kennylixi/gadmin/internal/modules/system/dao/internal"
)

// internalRoleDeptDao is internal type for wrapping internal DAO implements.
type internalRoleDeptDao = *internal.RoleDeptDao

// roleDeptDao is the data access object for table sys_role_dept.
// You can define custom methods on it to extend its functionality as you wish.
type roleDeptDao struct {
	internalRoleDeptDao
}

var (
	// RoleDept is globally public accessible object for table sys_role_dept operations.
	RoleDept = roleDeptDao{
		internal.NewRoleDeptDao(),
	}
)

// Fill with you ideas below.
