// ============================================================================
// This is auto-generated by gen tool only once. Fill this file as you wish.
// 数据库备份表Dao
// @author kennylixi
// @date 2023-05-07 13:31:59
// ============================================================================

package dao

import "github.com/kennylixi/gadmin/internal/modules/system/dao/internal"

// internalSqlBackupsDao is internal type for wrapping internal DAO implements.
type internalSqlBackupsDao = *internal.SqlBackupsDao

// sqlBackupsDao is the data access object for table sys_job.
// You can define custom methods on it to extend its functionality as you wish.
type sqlBackupsDao struct {
	internalSqlBackupsDao
}

var (
	// SqlBackups is globally public accessible object for table sys_sql_backups operations.
	SqlBackups = sqlBackupsDao{
		internal.NewSqlBackupsDao(),
	}
)

// Fill with you ideas below.
