// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// Api is the golang structure of table sys_api for DAO operations like Where/Data.
type Api struct {
	g.Meta    `orm:"table:sys_api, do:true"`
	ApiId     interface{} // 接口ID
	ApiModule interface{} // 业务模块
	ApiName   interface{} // 接口名称
	ApiMethod interface{} // 请求方法
	ApiUrl    interface{} // 接口地址
	CreateBy  interface{} // 创建者
	CreatedAt *gtime.Time // 创建时间
	UpdateBy  interface{} // 更新者
	UpdatedAt *gtime.Time // 更新时间
	Remark    interface{} // 备注
}
