// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// District is the golang structure of table sys_district for DAO operations like Where/Data.
type District struct {
	g.Meta      `orm:"table:sys_district, do:true"`
	Id          interface{} // 编号
	ParentId    interface{} // 上级编号
	Ancestors   interface{} // 祖级列表
	Name        interface{} // 地区名称
	Center      interface{} // 经纬度
	Citycode    interface{} // 城市编码
	Adcode      interface{} // 邮编
	Pinyin      interface{} // 拼音
	FirstPinyin interface{} // 拼音第一个字母
	Level       interface{} // 级别
	Status      interface{} // 是否开放
	OrderNum    interface{} // 排序
	CreateBy    interface{} // 创建者
	CreatedAt   *gtime.Time // 创建时间
	UpdateBy    interface{} // 更新者
	UpdatedAt   *gtime.Time // 更新时间
	DeletedAt   *gtime.Time // 删除时间
}
