// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// File is the golang structure of table sys_file for DAO operations like Where/Data.
type File struct {
	g.Meta    `orm:"table:sys_file, do:true"`
	Id        interface{} // ID
	DriverId  interface{} // 文件驱动ID
	Key       interface{} // 存储文件名
	Size      interface{} // 大小
	Type      interface{} // 文件类型
	Name      interface{} // 原文件名
	OwnerId   interface{} // 拥有者ID
	UserType  interface{} // 用户类型
	CreatedAt *gtime.Time // 创建时间
}
