// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/encoding/gjson"
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// FileDriver is the golang structure of table sys_file_driver for DAO operations like Where/Data.
type FileDriver struct {
	g.Meta    `orm:"table:sys_file_driver, do:true"`
	Id        interface{} // 编号
	Name      interface{} // 配置名
	Driver    interface{} // 存储器
	Remark    interface{} // 备注
	Master    interface{} // 是否为主配置
	Config    *gjson.Json // 存储配置
	CreateBy  interface{} // 创建者
	CreatedAt *gtime.Time // 创建时间
	UpdateBy  interface{} // 更新者
	UpdatedAt *gtime.Time // 更新时间
	DeletedAt *gtime.Time // 删除时间
}
