// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// Job is the golang structure of table sys_job for DAO operations like Where/Data.
type Job struct {
	g.Meta         `orm:"table:sys_job, do:true"`
	JobId          interface{} // 任务ID
	JobName        interface{} // 任务名称
	JobGroup       interface{} // 任务组名
	InvokeTarget   interface{} // 调用目标字符串
	InvokeParams   interface{} // 调用目标参数
	CronExpression interface{} // cron执行表达式
	MaxRetry       interface{} // 重试次数
	RetryDelay     interface{} // 重试间隔
	IsRecordLog    interface{} // 是否记录执行日志
	Status         interface{} // 状态（0正常 1暂停）
	CreateBy       interface{} // 创建者
	CreatedAt      *gtime.Time // 创建时间
	UpdateBy       interface{} // 更新者
	UpdatedAt      *gtime.Time // 更新时间
	Remark         interface{} // 备注信息
}
