// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// JobLog is the golang structure of table sys_job_log for DAO operations like Where/Data.
type JobLog struct {
	g.Meta        `orm:"table:sys_job_log, do:true"`
	JobLogId      interface{} // 任务日志ID
	InvokeTarget  interface{} // 调用目标字符串
	InvokeParams  interface{} // 调用目标参数
	JobMessage    interface{} // 日志信息
	Status        interface{} // 执行状态（0正常 1失败）
	ExceptionInfo interface{} // 异常信息
	CreatedAt     *gtime.Time // 创建时间
}
