// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// MenuApi is the golang structure of table sys_menu_api for DAO operations like Where/Data.
type MenuApi struct {
	g.Meta `orm:"table:sys_menu_api, do:true"`
	MenuId interface{} // 菜单ID
	ApiId  interface{} // 接口ID
}
