// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// PushType is the golang structure of table sys_push_type for DAO operations like Where/Data.
type PushType struct {
	g.Meta         `orm:"table:sys_push_type, do:true"`
	Id             interface{} //
	ParentId       interface{} // 上级编号
	Ancestors      interface{} // 祖级列表
	Name           interface{} // 类型名称
	Code           interface{} // 类型编码
	Status         interface{} // 状态（0开启 1禁用）
	Sort           interface{} // 排序
	Config         interface{} // 配置范例
	TemplateParams interface{} // 模板参数
	CreateBy       interface{} // 创建者
	CreatedAt      *gtime.Time // 创建时间
	UpdateBy       interface{} // 更新者
	UpdatedAt      *gtime.Time // 更新时间
}
