// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// PushChannel is the golang structure of table sys_push_channel for DAO operations like Where/Data.
type PushChannel struct {
	g.Meta    `orm:"table:sys_push_channel, do:true"`
	Id        interface{} // 编号
	Name      interface{} // 渠道名称
	TypeId    interface{} // 渠道类型
	Remark    interface{} // 备注
	Status    interface{} // 状态（0开启 1禁用）
	Config    interface{} // 渠道配置
	CreateBy  interface{} // 创建者
	CreatedAt *gtime.Time // 创建时间
	UpdateBy  interface{} // 更新者
	UpdatedAt *gtime.Time // 更新时间
}
