// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// UserOnline is the golang structure of table sys_user_online for DAO operations like Where/Data.
type UserOnline struct {
	g.Meta        `orm:"table:sys_user_online, do:true"`
	Id            interface{} //
	TokenId       interface{} // 用户标识
	Token         interface{} // 用户token
	UserName      interface{} // 用户名
	Ipaddr        interface{} // 登录ip
	LoginLocation interface{} // 登录地方
	Browser       interface{} // 浏览器
	Os            interface{} // 操作系统
	LoginTime     *gtime.Time // 登录时间
}
