// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package logic

import (
	_ "github.com/kennylixi/gadmin/internal/modules/common/logic/bizctx"
	_ "github.com/kennylixi/gadmin/internal/modules/common/logic/captcha"
	_ "github.com/kennylixi/gadmin/internal/modules/common/logic/ip"
	_ "github.com/kennylixi/gadmin/internal/modules/common/logic/password"
)
