// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// File is the golang structure for table file.
type File struct {
	Id        int64       `json:"id"        description:"ID"`
	DriverId  int64       `json:"driverId"  description:"文件驱动ID"`
	Key       string      `json:"key"       description:"存储文件名"`
	Size      int64       `json:"size"      description:"大小"`
	Type      string      `json:"type"      description:"文件类型"`
	Name      string      `json:"name"      description:"原文件名"`
	OwnerId   int64       `json:"ownerId"   description:"拥有者ID"`
	UserType  string      `json:"userType"  description:"用户类型"`
	CreatedAt *gtime.Time `json:"createdAt" description:"创建时间"`
}
