// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/encoding/gjson"
	"github.com/gogf/gf/v2/os/gtime"
)

// FileDriver is the golang structure for table file_driver.
type FileDriver struct {
	Id        int64       `json:"id"        description:"编号"`
	Name      string      `json:"name"      description:"配置名"`
	Driver    string      `json:"driver"    description:"存储器"`
	Remark    string      `json:"remark"    description:"备注"`
	Master    bool        `json:"master"    description:"是否为主配置"`
	Config    *gjson.Json `json:"config"    description:"存储配置"`
	CreateBy  string      `json:"createBy"  description:"创建者"`
	CreatedAt *gtime.Time `json:"createdAt" description:"创建时间"`
	UpdateBy  string      `json:"updateBy"  description:"更新者"`
	UpdatedAt *gtime.Time `json:"updatedAt" description:"更新时间"`
	DeletedAt *gtime.Time `json:"deletedAt" description:"删除时间"`
}
