// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// Job is the golang structure for table job.
type Job struct {
	JobId          int64       `json:"jobId"          description:"任务ID"`
	JobName        string      `json:"jobName"        description:"任务名称"`
	JobGroup       string      `json:"jobGroup"       description:"任务组名"`
	InvokeTarget   string      `json:"invokeTarget"   description:"调用目标字符串"`
	InvokeParams   string      `json:"invokeParams"   description:"调用目标参数"`
	CronExpression string      `json:"cronExpression" description:"cron执行表达式"`
	MaxRetry       int         `json:"maxRetry"       description:"重试次数"`
	RetryDelay     int         `json:"retryDelay"     description:"重试间隔"`
	IsRecordLog    bool        `json:"isRecordLog"    description:"是否记录执行日志"`
	Status         string      `json:"status"         description:"状态（0正常 1暂停）"`
	CreateBy       string      `json:"createBy"       description:"创建者"`
	CreatedAt      *gtime.Time `json:"createdAt"      description:"创建时间"`
	UpdateBy       string      `json:"updateBy"       description:"更新者"`
	UpdatedAt      *gtime.Time `json:"updatedAt"      description:"更新时间"`
	Remark         string      `json:"remark"         description:"备注信息"`
}
