// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// JobLog is the golang structure for table job_log.
type JobLog struct {
	JobLogId      int64       `json:"jobLogId"      description:"任务日志ID"`
	InvokeTarget  string      `json:"invokeTarget"  description:"调用目标字符串"`
	InvokeParams  string      `json:"invokeParams"  description:"调用目标参数"`
	JobMessage    string      `json:"jobMessage"    description:"日志信息"`
	Status        string      `json:"status"        description:"执行状态（0正常 1失败）"`
	ExceptionInfo string      `json:"exceptionInfo" description:"异常信息"`
	CreatedAt     *gtime.Time `json:"createdAt"     description:"创建时间"`
}
