// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// MenuApi is the golang structure for table menu_api.
type MenuApi struct {
	MenuId int64 `json:"menuId" description:"菜单ID"`
	ApiId  int64 `json:"apiId"  description:"接口ID"`
}
