// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// PushChannel is the golang structure for table push_channel.
type PushChannel struct {
	Id        int64       `json:"id"        description:"编号"`
	Name      string      `json:"name"      description:"渠道名称"`
	TypeId    int64       `json:"typeId"    description:"渠道类型"`
	Remark    string      `json:"remark"    description:"备注"`
	Status    string      `json:"status"    description:"状态（0开启 1禁用）"`
	Config    string      `json:"config"    description:"渠道配置"`
	CreateBy  string      `json:"createBy"  description:"创建者"`
	CreatedAt *gtime.Time `json:"createdAt" description:"创建时间"`
	UpdateBy  string      `json:"updateBy"  description:"更新者"`
	UpdatedAt *gtime.Time `json:"updatedAt" description:"更新时间"`
}
