// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// PushType is the golang structure for table push_type.
type PushType struct {
	Id             int64       `json:"id"             description:""`
	ParentId       int64       `json:"parentId"       description:"上级编号"`
	Ancestors      string      `json:"ancestors"      description:"祖级列表"`
	Name           string      `json:"name"           description:"类型名称"`
	Code           string      `json:"code"           description:"类型编码"`
	Status         string      `json:"status"         description:"状态（0开启 1禁用）"`
	Sort           int         `json:"sort"           description:"排序"`
	Config         string      `json:"config"         description:"配置范例"`
	TemplateParams string      `json:"templateParams" description:"模板参数"`
	CreateBy       string      `json:"createBy"       description:"创建者"`
	CreatedAt      *gtime.Time `json:"createdAt"      description:"创建时间"`
	UpdateBy       string      `json:"updateBy"       description:"更新者"`
	UpdatedAt      *gtime.Time `json:"updatedAt"      description:"更新时间"`
}
