// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// PushTemplate is the golang structure for table push_template.
type PushTemplate struct {
	Id        int64       `json:"id"        description:"编号"`
	Name      string      `json:"name"      description:"模板名称"`
	Code      string      `json:"code"      description:"模板编码"`
	ChannelId int64       `json:"channelId" description:"渠道ID"`
	Params    string      `json:"params"    description:"渠道信息"`
	Status    string      `json:"status"    description:"状态（0开启 1禁用）"`
	Cron      string      `json:"cron"      description:"执行时间(0实时，定时cron表达式)"`
	MsgType   string      `json:"msgType"   description:"消息类型"`
	Remark    string      `json:"remark"    description:"备注"`
	CreateBy  string      `json:"createBy"  description:"创建者"`
	CreatedAt *gtime.Time `json:"createdAt" description:"创建时间"`
	UpdateBy  string      `json:"updateBy"  description:"更新者"`
	UpdatedAt *gtime.Time `json:"updatedAt" description:"更新时间"`
}
