// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// RoleApi is the golang structure for table role_api.
type RoleApi struct {
	RoleId int64 `json:"roleId" description:"角色ID"`
	ApiId  int64 `json:"apiId"  description:"接口ID"`
}
