// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// RoleMenu is the golang structure for table role_menu.
type RoleMenu struct {
	RoleId int64 `json:"roleId" description:"角色ID"`
	MenuId int64 `json:"menuId" description:"菜单ID"`
}
