// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// RoleDept is the golang structure for table role_dept.
type RoleDept struct {
	RoleId int64 `json:"roleId" description:"角色ID"`
	DeptId int64 `json:"deptId" description:"部门ID"`
}
