// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// SqlBackups is the golang structure for table sql_backups.
type SqlBackups struct {
	BackupsId int64       `json:"backupsId" description:"备份ID"`
	FileName  string      `json:"fileName"  description:"文件名称"`
	Password  string      `json:"password"  description:"加密密码"`
	FileSize  uint64      `json:"fileSize"  description:"文件大小"`
	CreatedAt *gtime.Time `json:"createdAt" description:"备份时间"`
}
