// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// UserOnline is the golang structure for table user_online.
type UserOnline struct {
	Id            int64       `json:"id"            description:""`
	TokenId       string      `json:"tokenId"       description:"用户标识"`
	Token         string      `json:"token"         description:"用户token"`
	UserName      string      `json:"userName"      description:"用户名"`
	Ipaddr        string      `json:"ipaddr"        description:"登录ip"`
	LoginLocation string      `json:"loginLocation" description:"登录地方"`
	Browser       string      `json:"browser"       description:"浏览器"`
	Os            string      `json:"os"            description:"操作系统"`
	LoginTime     *gtime.Time `json:"loginTime"     description:"登录时间"`
}
