// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// UserRole is the golang structure for table user_role.
type UserRole struct {
	UserId int64 `json:"userId" description:"用户ID"`
	RoleId int64 `json:"roleId" description:"角色ID"`
}
