// ============================================================================
// This is auto-generated by gen tool only once. Fill this file as you wish.
// 接口管理Model数据层
// @author kennylixi
// @date 2023-05-14 11:01:08
// ============================================================================

package model

import "github.com/kennylixi/gadmin/internal/modules/system/model/entity"

// Fill with you ideas below.

// ApiListInput 查询列表入参
type ApiListInput struct {
	ApiName   string `json:"apiName"`   // 接口名称
	ApiModule string `json:"apiModule"` // 业务模块
	ApiUrl    string `json:"apiUrl"`    // 接口地址
	ApiMethod string `json:"apiMethod"` // 请求方法
}

// ApiListOutput 查询列表出参
type ApiListOutput struct {
	List  []*entity.Api `json:"list"`  // 列表
	Total int           `json:"total"` // 数据总数
}

// ApiAddInput 新增入参
type ApiAddInput struct {
	ApiName   string `json:"apiName"`   // 接口名称
	ApiModule string `json:"apiModule"` // 业务模块
	ApiUrl    string `json:"apiUrl"`    // 接口地址
	ApiMethod string `json:"apiMethod"` // 请求方法
	CreateBy  string `json:"createBy"`  // 创建者
	Remark    string `json:"remark"`    // 备注
}

// ApiEditInput 修改入参
type ApiEditInput struct {
	ApiId     int64  `json:"apiId"`     // 接口ID
	ApiName   string `json:"apiName"`   // 接口名称
	ApiModule string `json:"apiModule"` // 业务模块
	ApiUrl    string `json:"apiUrl"`    // 接口地址
	ApiMethod string `json:"apiMethod"` // 请求方法
	UpdateBy  string `json:"updateBy"`  // 更新者
	Remark    string `json:"remark"`    // 备注
}
