// ============================================================================
// This is auto-generated by gen tool only once. Fill this file as you wish.
// 驱动配置Model数据层
// @author kennylixi
// @date 2023-03-23 14:15:08
// ============================================================================

package model

import (
	"github.com/kennylixi/gadmin/internal/modules/system/model/entity"

	"github.com/gogf/gf/v2/encoding/gjson"
)

// Fill with you ideas below.

// FileDriverListInput 查询列表入参
type FileDriverListInput struct {
	Name   string `json:"name"`   // 驱动名称
	Driver string `json:"driver"` // 驱动类型
}

// FileDriverListOutput 查询列表出参
type FileDriverListOutput struct {
	List  []*entity.FileDriver `json:"list"`  // 列表
	Total int                  `json:"total"` // 数据总数
}

// FileDriverAddInput 新增入参
type FileDriverAddInput struct {
	Name     string      `json:"name"`     // 驱动名称
	Driver   string      `json:"driver"`   // 驱动类型
	Remark   string      `json:"remark"`   // 备注
	Master   int         `json:"master"`   // 默认驱动
	Config   *gjson.Json `json:"config"`   // 驱动配置
	CreateBy string      `json:"createBy"` // 创建者
}

// FileDriverEditInput 修改入参
type FileDriverEditInput struct {
	Id       int64       `json:"id"`       // 编号
	Name     string      `json:"name"`     // 驱动名称
	Driver   string      `json:"driver"`   // 驱动类型
	Remark   string      `json:"remark"`   // 备注
	Master   int         `json:"master"`   // 默认驱动
	Config   *gjson.Json `json:"config"`   // 驱动配置
	UpdateBy string      `json:"updateBy"` // 更新者
}
