// ============================================================================
// This is auto-generated by gen tool only once. Fill this file as you wish.
// 文件管理Model数据层
// @author kennylixi
// @date 2023-03-23 14:14:45
// ============================================================================

package model

import (
	"github.com/gogf/gf/v2/net/ghttp"
	"github.com/kennylixi/gadmin/internal/modules/system/model/entity"
)

// Fill with you ideas below.

type File struct {
	entity.File
	DriverName string `json:"driverName"`
}

// FileListInput 查询列表入参
type FileListInput struct {
	Key string `json:"key"` // 存储文件名
}

// FileListOutput 查询列表出参
type FileListOutput struct {
	List  []*File `json:"list"`  // 列表
	Total int     `json:"total"` // 数据总数
}

// FileAddInput 新增入参
type FileAddInput struct {
	DriverId int64  `json:"driverId"` // 驱动
	Key      string `json:"key"`      // 存储文件名
	Size     int64  `json:"size"`     // 大小
	Type     string `json:"type"`     // 文件类型
	Name     string `json:"name"`     // 原文件名
	OwnerId  int64  `json:"ownerId"`  // 拥有者ID
	UserType string `json:"userType"` // 用户类型
}

// FileEditInput 修改入参
type FileEditInput struct {
	Id       int64  `json:"id"`       // ID
	DriverId int64  `json:"driverId"` // 文件驱动ID
	Key      string `json:"key"`      // 存储文件名
	Size     int64  `json:"size"`     // 大小
	Type     string `json:"type"`     // 文件类型
	Name     string `json:"name"`     // 原文件名
	OwnerId  int64  `json:"ownerId"`  // 拥有者ID
	UserType string `json:"userType"` // 用户类型
}

type FileUploadInput struct {
	File             *ghttp.UploadFile // 上传的文件
	AllowedExtension []string          // 允许的扩展名
	OwnerId          int64             // 归属ID
	UserType         string            // 归属ID账号类型

}
type FileUploadOutput struct {
	Url         string `json:"url"`         // 访问地址
	FileName    string `json:"fileName"`    // 文件名
	NewFileName string `json:"newFileName"` // 新文件名
	Name        string `json:"name"`        // 原文件名
}

type FileSaveByBytesInput struct {
	FileBytes        []byte   // 上传的文件
	Ext              string   //
	AllowedExtension []string // 允许的扩展名
}
type FileSaveByBytesOutput struct {
	FileName string `json:"fileName"` // 文件名
}
