// ============================================================================
// This is auto-generated by gen tool only once. Fill this file as you wish.
// 渠道管理Model数据层
// @author kennylixi
// @date 2023-03-27 08:32:42
// ============================================================================

package model

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// Fill with you ideas below.

type PushChannelListItem struct {
	Id         int64       `json:"id"         description:"编号"`
	Name       string      `json:"name"       description:"渠道名称"`
	Status     string      `json:"status"     description:"渠道状态"`
	TypeId     int64       `json:"typeId"     description:"渠道类型"`
	TypeCode   string      `json:"typeCode"   description:"渠道类型编码"`
	TypeName   string      `json:"typeName"   description:"渠道类型名称"`
	TypeStatus string      `json:"typeStatus" description:"渠道类型状态"`
	Config     string      `json:"config"     description:"渠道配置"`
	Remark     string      `json:"remark"     description:"备注"`
	CreatedAt  *gtime.Time `json:"createdAt"  description:"创建时间"`
}

type PushChannelSimpleListItem struct {
	Id       int64  `json:"id"        description:"编号"`
	Name     string `json:"name"      description:"渠道名称"`
	TypeName string `json:"typeName"  description:"渠道类型名称"`
}

// PushChannelSimpleListInput 查询列表入参
type PushChannelSimpleListInput struct {
	Name   string `json:"name"`   // 渠道名称
	TypeId int64  `json:"typeId"` // 渠道类型
	Status string `json:"status"` // 状态
}

// PushChannelSimpleListOutput 查询列表出参
type PushChannelSimpleListOutput []*PushChannelSimpleListItem

// PushChannelListInput 查询列表入参
type PushChannelListInput struct {
	Name   string `json:"name"`   // 渠道名称
	TypeId int64  `json:"typeId"` // 渠道类型
	Status string `json:"status"` // 状态
}

// PushChannelListOutput 查询列表出参
type PushChannelListOutput struct {
	List  []*PushChannelListItem `json:"list"`  // 列表
	Total int                    `json:"total"` // 数据总数
}

type PushTemplateTestInput struct {
	Id             int64             // 模板ID
	Account        string            // 接收者账号
	TemplateParams map[string]string // 模板参数
}

// PushChannelAddInput 新增入参
type PushChannelAddInput struct {
	Name     string `json:"name"`     // 渠道名称
	TypeId   int64  `json:"typeId"`   // 渠道类型
	Remark   string `json:"remark"`   // 备注
	Status   string `json:"status"`   // 状态
	Config   string `json:"config"`   // 渠道配置
	CreateBy string `json:"createBy"` // 创建者
}

// PushChannelEditInput 修改入参
type PushChannelEditInput struct {
	Id       int64  `json:"id"`       // 编号
	Name     string `json:"name"`     // 渠道名称
	TypeId   int64  `json:"typeId"`   // 渠道类型
	Remark   string `json:"remark"`   // 备注
	Status   string `json:"status"`   // 状态
	Config   string `json:"config"`   // 渠道配置
	UpdateBy string `json:"updateBy"` // 更新者
}
