// ============================================================================
// This is auto-generated by gen tool only once. Fill this file as you wish.
// 消息模板Model数据层
// @author kennylixi
// @date 2023-03-29 15:55:04
// ============================================================================

package model

import (
	"github.com/kennylixi/gadmin/internal/modules/system/model/entity"
)

// Fill with you ideas below.

type PushTemplate struct {
	entity.PushTemplate
	TypeStatus    string `json:"typeStatus"`
	TypeName      string `json:"typeName"`
	ChannelStatus string `json:"channelStatus"`
	ChannelName   string `json:"channelName"`
}

// PushTemplateListInput 查询列表入参
type PushTemplateListInput struct {
	Name      string `json:"name"`      // 模板名称
	Code      string `json:"code"`      // 模板编码
	ChannelId int64  `json:"channelId"` // 渠道ID
	MsgType   string `json:"msgType"`   // 消息类型
	Status    string `json:"status"`    // 模板状态
}

// PushTemplateListOutput 查询列表出参
type PushTemplateListOutput struct {
	List  []*PushTemplate `json:"list"`  // 列表
	Total int             `json:"total"` // 数据总数
}

// PushTemplateAddInput 新增入参
type PushTemplateAddInput struct {
	Name      string `json:"name"`      // 模板名称
	Code      string `json:"code"`      // 模板编码
	ChannelId int64  `json:"channelId"` // 渠道ID
	Params    string `json:"params"`    // 渠道信息
	Cron      string `json:"cron"`      // 立即执行
	MsgType   string `json:"msgType"`   // 消息类型
	Remark    string `json:"remark"`    // 备注
	CreateBy  string `json:"createBy"`  // 创建者
}

// PushTemplateEditInput 修改入参
type PushTemplateEditInput struct {
	Id        int64  `json:"id"`        // 编号
	Name      string `json:"name"`      // 模板名称
	Code      string `json:"code"`      // 模板编码
	ChannelId int64  `json:"channelId"` // 渠道ID
	Params    string `json:"params"`    // 渠道信息
	Cron      string `json:"cron"`      // 立即执行
	MsgType   string `json:"msgType"`   // 消息类型
	Remark    string `json:"remark"`    // 备注
	UpdateBy  string `json:"updateBy"`  // 更新者
}
