// ============================================================================
// This is auto-generated by gen tool only once. Fill this file as you wish.
// 行业管理Model数据层
// @author kennylixi
// @date 2023-02-22 10:47:28
// ============================================================================

package model

import (
	"github.com/kennylixi/gadmin/internal/modules/system/model/entity"
)

// Fill with you ideas below.

type PushType struct {
	entity.PushType
	Children []*PushType `json:"children"`
}

type PushTypeItem struct {
	Id   int64  `json:"id"`
	Name string `json:"name"`
}

// PushTypeListInput 查询列表入参
type PushTypeListInput struct {
	Name     string
	ParentId int64  // 上级ID
	Status   string // 状态
}

// PushTypeListOutput 查询列表出参
type PushTypeListOutput []*PushType

// PushTypeAddInput 新增入参
type PushTypeAddInput struct {
	ParentId       int64  // 上级编号
	Name           string // 名称
	Code           string // 编码
	Status         string // 状态
	Sort           int    // 排序
	Config         string // 配置
	TemplateParams string // 模板
	CreateBy       string // 创建者
}

// PushTypeEditInput 修改入参
type PushTypeEditInput struct {
	Id             int64
	ParentId       int64  // 上级编号
	Name           string // 名称
	Code           string // 编码
	Status         string // 状态
	Sort           int    // 排序
	Config         string // 配置
	TemplateParams string // 模板
	UpdateBy       string // 更新者
}
