// ============================================================================
// This is auto-generated by gen tool only once. Fill this file as you wish.
// 数据库备份表Model数据层
// @author kennylixi
// @date 2023-05-07 13:31:59
// ============================================================================

package model

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// Fill with you ideas below.

type SqlBackupsCfg struct {
	Path          string
	Tables        []string
	ExcludeTables []string
	Args          string
}

type SqlBackupsListItem struct {
	BackupsId int64       `json:"backupsId" description:"备份ID"`
	FileName  string      `json:"fileName"  description:"文件名称"`
	FileSize  uint64      `json:"fileSize"  description:"文件大小"`
	CreatedAt *gtime.Time `json:"createdAt" description:"备份时间"`
}

// SqlBackupsListInput 查询列表入参
type SqlBackupsListInput struct {
	FileName string `json:"fileName"`
}

// SqlBackupsListOutput 查询列表出参
type SqlBackupsListOutput struct {
	List  []*SqlBackupsListItem `json:"list"`  // 列表
	Total int                   `json:"total"` // 数据总数
}

// SqlBackupsAddInput 新增入参
type SqlBackupsAddInput struct {
	FileName string `json:"fileName"` // 文件名
	FileSize uint   `json:"fileSize"` // 文件大小
}

// SqlBackupsEditInput 修改入参
type SqlBackupsEditInput struct {
	BackupsId int64 `json:"backupsId"` // 备份ID
}
