// ============================================================================
// This is auto-generated by gen tool only once. Fill this file as you wish.
// 接口管理 API操作定义
// @author kennylixi
// @date 2023-05-14 11:01:08
// ============================================================================

package admin

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/kennylixi/gadmin/internal/modules/common/model"
	"github.com/kennylixi/gadmin/internal/modules/system/model/entity"
)

// ApiListReq 查询接口管理列表
type ApiListReq struct {
	g.Meta    `path:"/api/list" tags:"接口管理" method:"get" summary:"查询接口管理列表"`
	ApiName   string // 接口名称
	ApiModule string // 业务模块
	ApiUrl    string // 接口地址
	ApiMethod string // 请求方法
}
type ApiListRes struct {
	List  []*entity.Api `json:"list"`  // 列表
	Total int           `json:"total"` // 数据总数
}

// ApiModuleListReq 查询接口模块列表
type ApiModuleListReq struct {
	g.Meta `path:"/api/module/list" tags:"接口管理" method:"get" summary:"查询接口模块列表"`
}
type ApiModuleListRes []string

// ApiGetInfoReq 获取接口管理详情
type ApiGetInfoReq struct {
	g.Meta `path:"/api/{ApiId}" tags:"接口管理" method:"get" summary:"获取接口管理详情"`
	ApiId  int64
}
type ApiGetInfoRes entity.Api

// ApiReImportReq 重新导入所有接口
type ApiReImportReq struct {
	g.Meta `path:"/api/reimport" tags:"接口管理" method:"put" summary:"重新导入所有接口"`
}
type ApiReImportRes struct {
}

// ApiTreeselectReq 获取接口树形结构
type ApiTreeselectReq struct {
	g.Meta `path:"/api/treeselect" tags:"接口管理" method:"get" summary:"获取接口树形结构"`
}
type ApiTreeselectRes []*model.TreeSelect

// ApiRoleApiTreeselectReq 获取角色接口列表（树形结构）
type ApiRoleApiTreeselectReq struct {
	g.Meta `path:"/api/roleApiTreeselect/:RoleId" tags:"接口管理" method:"get" summary:"获取角色接口列表（树形结构）"`
	RoleId int64
}
type ApiRoleApiTreeselectRes struct {
	CheckedKeys []int64             `json:"checkedKeys"`
	Apis        []*model.TreeSelect `json:"apis"`
}

// ApiAddReq 新增接口管理
type ApiAddReq struct {
	g.Meta    `path:"/api" tags:"接口管理" method:"post" summary:"新增接口管理"`
	ApiName   string // 接口名称
	ApiModule string // 业务模块
	ApiUrl    string // 接口地址
	ApiMethod string // 请求方法
	Remark    string // 备注
}
type ApiAddRes struct {
}

// ApiEditReq 修改接口管理
type ApiEditReq struct {
	g.Meta    `path:"/api" tags:"接口管理" method:"put" summary:"修改接口管理"`
	ApiId     int64  `v:"required#请输入接口管理Id"` // 接口管理ID
	ApiName   string // 接口名称
	ApiModule string // 业务模块
	ApiUrl    string // 接口地址
	ApiMethod string // 请求方法
	Remark    string // 备注
}
type ApiEditRes struct {
}

// ApiDeleteReq 删除接口管理
type ApiDeleteReq struct {
	g.Meta `path:"/api" tags:"接口管理" method:"delete" summary:"删除接口管理"`
	ApiIds []int64
}
type ApiDeleteRes struct {
}
