// ============================================================================
// This is auto-generated by gen tool only once. Fill this file as you wish.
// 文件管理 API操作定义
// @author kennylixi
// @date 2023-03-23 14:14:45
// ============================================================================

package admin

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/kennylixi/gadmin/internal/modules/system/model"
	"github.com/kennylixi/gadmin/internal/modules/system/model/entity"
)

// FileListReq 查询文件管理列表
type FileListReq struct {
	g.Meta `path:"/file/list" tags:"文件管理" method:"get" summary:"查询文件管理列表"`
	Key    string // 存储文件名
}
type FileListRes struct {
	List  []*model.File `json:"list"`  // 列表
	Total int           `json:"total"` // 数据总数
}

// FileGetInfoReq 获取文件管理详情
type FileGetInfoReq struct {
	g.Meta `path:"/file/{Id}" tags:"文件管理" method:"get" summary:"获取文件管理详情"`
	Id     int64
}
type FileGetInfoRes entity.File

// FileDeleteReq 删除文件管理
type FileDeleteReq struct {
	g.Meta `path:"/file" tags:"文件管理" method:"delete" summary:"删除文件管理"`
	Ids    []int64
}
type FileDeleteRes struct {
}
