// ============================================================================
// This is auto-generated by gen tool only once. Fill this file as you wish.
// 驱动配置 API操作定义
// @author kennylixi
// @date 2023-03-23 14:15:08
// ============================================================================

package admin

import (
	"github.com/gogf/gf/v2/encoding/gjson"
	"github.com/kennylixi/gadmin/internal/modules/system/model/entity"

	"github.com/gogf/gf/v2/frame/g"
)

// FileDriverListReq 查询驱动配置列表
type FileDriverListReq struct {
	g.Meta `path:"/fileDriver/list" tags:"文件驱动配置" method:"get" summary:"查询驱动配置列表"`
	Name   string // 驱动名称
	Driver string // 驱动类型
}
type FileDriverListRes struct {
	List  []*entity.FileDriver `json:"list"`  // 列表
	Total int                  `json:"total"` // 数据总数
}

// FileDriverGetInfoReq 获取驱动配置详情
type FileDriverGetInfoReq struct {
	g.Meta `path:"/fileDriver/{Id}" tags:"文件驱动配置" method:"get" summary:"获取驱动配置详情"`
	Id     int64
}
type FileDriverGetInfoRes entity.FileDriver

// FileDriverAddReq 新增驱动配置
type FileDriverAddReq struct {
	g.Meta `path:"/fileDriver" tags:"文件驱动配置" method:"post" summary:"新增驱动配置"`
	Name   string      `v:"required#请输入驱动名称"` // 驱动名称
	Driver string      `v:"required#请输入驱动类型"` // 驱动类型
	Master int         `v:"required#请输入默认驱动"` // 默认驱动
	Config *gjson.Json `v:"required#请输入驱动配置"` // 驱动配置
	Remark string      // 备注
}
type FileDriverAddRes struct {
}

// FileDriverEditReq 修改驱动配置
type FileDriverEditReq struct {
	g.Meta `path:"/fileDriver" tags:"文件驱动配置" method:"put" summary:"修改驱动配置"`
	Id     int64       `v:"required#请输入驱动配置Id"` // 驱动配置ID
	Name   string      `v:"required#请输入驱动名称"`   // 驱动名称
	Driver string      `v:"required#请输入驱动类型"`   // 驱动类型
	Master int         `v:"required#请输入默认驱动"`   // 默认驱动
	Config *gjson.Json `v:"required#请输入驱动配置"`   // 驱动配置
	Remark string      // 备注
}
type FileDriverEditRes struct {
}

// FileDriverDeleteReq 删除驱动配置
type FileDriverDeleteReq struct {
	g.Meta `path:"/fileDriver" tags:"文件驱动配置" method:"delete" summary:"删除驱动配置"`
	Ids    []int64
}
type FileDriverDeleteRes struct {
}

// FileDriverMasterReq 设置主驱动配置
type FileDriverMasterReq struct {
	g.Meta `path:"/fileDriver/master/{Id}" tags:"文件驱动配置" method:"put" summary:"设置主驱动配置"`
	Id     int64
}
type FileDriverMasterRes struct {
}

// FileDriverTestReq 测试驱动配置
type FileDriverTestReq struct {
	g.Meta `path:"/fileDriver/test/{Id}" tags:"文件驱动配置" method:"put" summary:"测试驱动配置"`
	Id     int64
}
type FileDriverTestRes struct {
}
