// ============================================================================
// This is auto-generated by gen tool only once. Fill this file as you wish.
// 消息模板 API操作定义
// @author kennylixi
// @date 2023-03-29 15:55:04
// ============================================================================

package admin

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/kennylixi/gadmin/internal/modules/system/model"
	"github.com/kennylixi/gadmin/internal/modules/system/model/entity"
)

// PushTemplateListReq 查询消息模板列表
type PushTemplateListReq struct {
	g.Meta    `path:"/pushTemplate/list" tags:"消息模板" method:"get" summary:"查询消息模板列表"`
	Name      string // 模板名称
	Code      string // 模板编码
	ChannelId int64  // 渠道ID
	MsgType   string // 消息类型
}
type PushTemplateListRes struct {
	List  []*model.PushTemplate `json:"list"`  // 列表
	Total int                   `json:"total"` // 数据总数
}

// PushTemplateGetInfoReq 获取消息模板详情
type PushTemplateGetInfoReq struct {
	g.Meta `path:"/pushTemplate/{Id}" tags:"消息模板" method:"get" summary:"获取消息模板详情"`
	Id     int64
}
type PushTemplateGetInfoRes entity.PushTemplate

// PushTemplateTestReq 获取消息模板详情
type PushTemplateTestReq struct {
	g.Meta         `path:"/pushTemplate/test" tags:"消息模板" method:"post" summary:"测试发送模板消息"`
	Id             int64
	Account        string
	TemplateParams map[string]string
}
type PushTemplateTestRes struct{}

// PushTemplateAddReq 新增消息模板
type PushTemplateAddReq struct {
	g.Meta    `path:"/pushTemplate" tags:"消息模板" method:"post" summary:"新增消息模板"`
	Name      string `v:"required#请输入模板名称"` // 模板名称
	Code      string `v:"required#请输入模板编码"` // 模板编码
	ChannelId int64  `v:"required#请输入渠道ID"` // 渠道ID
	Params    string `v:"required#请输入渠道信息"` // 渠道信息
	Cron      string // 立即执行
	MsgType   string `v:"required|in:0,1,2#请输入消息类型|消息类型非法" d:"0"` // 消息类型
	Status    string `v:"in:0,1#状态非法" d:"0"`                      // 是否开放
	Remark    string // 备注
}
type PushTemplateAddRes struct {
}

// PushTemplateEditReq 修改消息模板
type PushTemplateEditReq struct {
	g.Meta    `path:"/pushTemplate" tags:"消息模板" method:"put" summary:"修改消息模板"`
	Id        int64  `v:"required#请输入消息模板Id"` // 消息模板ID
	Name      string `v:"required#请输入模板名称"`   // 模板名称
	Code      string `v:"required#请输入模板编码"`   // 模板编码
	ChannelId int64  `v:"required#请输入渠道ID"`   // 渠道ID
	Params    string `v:"required#请输入渠道信息"`   // 渠道信息
	Cron      string // 立即执行
	MsgType   string `v:"required|in:0,1,2#请输入消息类型|消息类型非法" d:"0"` // 消息类型
	Status    string `v:"in:0,1#状态非法" d:"0"`                      // 是否开放
	Remark    string // 备注
}
type PushTemplateEditRes struct {
}

// PushTemplateDeleteReq 删除消息模板
type PushTemplateDeleteReq struct {
	g.Meta `path:"/pushTemplate" tags:"消息模板" method:"delete" summary:"删除消息模板"`
	Ids    []int64
}
type PushTemplateDeleteRes struct {
}
