// ============================================================================
// This is auto-generated by gen tool only once. Fill this file as you wish.
// 推送渠道类型 API操作定义
// @author kennylixi
// @date 2023-02-22 10:47:28
// ============================================================================

package admin

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/kennylixi/gadmin/internal/modules/system/model"
	"github.com/kennylixi/gadmin/internal/modules/system/model/entity"
)

type PushTypeListReq struct {
	g.Meta   `path:"/pushType/list" tags:"推送渠道类型" method:"get" summary:"获取所有渠道类型"`
	Name     string
	ParentId int64  // 上级ID
	Status   string // 状态
}
type PushTypeListRes []*model.PushType

type PushTypeListByParentIdReq struct {
	g.Meta   `path:"/pushType/list/{ParentId}" tags:"推送渠道类型" method:"get" summary:"获取下级渠道类型"`
	ParentId int64
}
type PushTypeListByParentIdRes []*model.PushType

type PushTypeGetInfoReq struct {
	g.Meta `path:"/pushType/{Id}" tags:"推送渠道类型" method:"get" summary:"获取渠道类型详情"`
	Id     int64
}
type PushTypeGetInfoRes entity.PushType

type PushTypeAddReq struct {
	g.Meta         `path:"/pushType" tags:"推送渠道类型" method:"post" summary:"新增渠道类型"`
	ParentId       int64  `v:"min:0#请选择上级渠道类型"`   // 上级编号
	Name           string `v:"required#渠道类型名称必填"` // 渠道类型名称
	Code           string `v:"required#渠道类型编码必填"` // 编码
	Status         string `v:"in:0,1#状态非法" d:"0"` // 是否开放
	Config         string
	TemplateParams string // 模板
	Sort           int    // 排序
}
type PushTypeAddRes struct {
}

type PushTypeEditReq struct {
	g.Meta         `path:"/pushType" tags:"推送渠道类型" method:"put" summary:"修改渠道类型"`
	Id             int64  // 编号
	ParentId       int64  `v:"min:0#请选择上级渠道类型"`   // 上级编号
	Name           string `v:"required#渠道类型名称必填"` // 渠道类型名称
	Code           string `v:"required#渠道类型编码必填"` // 编码
	Status         string `v:"in:0,1#状态非法" d:"0"` // 是否开放
	Config         string
	TemplateParams string // 模板
	Sort           int    // 排序
}
type PushTypeEditRes struct {
}

type PushTypeDeleteReq struct {
	g.Meta `path:"/pushType/{id}" tags:"推送渠道类型" method:"delete" summary:"删除渠道类型"`
	Id     int64
}
type PushTypeDeleteRes struct {
}
