// ============================================================================
// This is auto-generated by gen tool only once. Fill this file as you wish.
// 数据库备份表 API操作定义
// @author kennylixi
// @date 2023-05-07 13:31:59
// ============================================================================

package admin

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/kennylixi/gadmin/internal/modules/system/model"
)

// SqlBackupsListReq 查询数据库备份表列表
type SqlBackupsListReq struct {
	g.Meta   `path:"/sqlBackups/list" tags:"数据库管理" method:"get" summary:"查询数据库备份表列表"`
	FileName string `json:"fileName"`
}
type SqlBackupsListRes struct {
	List  []*model.SqlBackupsListItem `json:"list"`  // 列表
	Total int                         `json:"total"` // 数据总数
}

// SqlBackupsBackUpReq 备份数据库
type SqlBackupsBackUpReq struct {
	g.Meta `path:"/sqlBackups" tags:"数据库管理" method:"post" summary:"备份数据库"`
}
type SqlBackupsBackUpRes struct {
}

// SqlBackupsPwdReq 获取密码
type SqlBackupsPwdReq struct {
	g.Meta    `path:"/sqlBackups/pwd/{BackupsId}" tags:"数据库管理" method:"get" summary:"获取备份文件解压密码"`
	BackupsId int64
}
type SqlBackupsPwdRes string

// SqlBackupsRecoverReq 恢复备份数据
type SqlBackupsRecoverReq struct {
	g.Meta    `path:"/sqlBackups/recover/{BackupsId}" tags:"数据库管理" method:"put" summary:"恢复数据库备份"`
	BackupsId int64
}
type SqlBackupsRecoverRes struct {
}

// SqlBackupsDeleteReq 删除数据库备份表
type SqlBackupsDeleteReq struct {
	g.Meta     `path:"/sqlBackups" tags:"数据库管理" method:"delete" summary:"删除数据库备份表"`
	BackupsIds []int64
}
type SqlBackupsDeleteRes struct {
}
