// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"context"
	"github.com/kennylixi/gadmin/internal/modules/common/model"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/net/ghttp"
)

type (
	IBizCtx interface {
		Init(r *ghttp.Request, customCtx *model.Context)
		Get(ctx context.Context) *model.Context
		GetUser(ctx context.Context) *model.ContextUser
		SetUser(ctx context.Context, ctxUser *model.ContextUser)
		GetUserId(ctx context.Context) int64
		GetDeptId(ctx context.Context) int64
		GetUserName(ctx context.Context) string
		SetData(ctx context.Context, data g.Map)
		SetNoPage(ctx context.Context)
		SetScopeData(ctx context.Context, scopeData string)
		ScopeData(ctx context.Context, model *gdb.Model) *gdb.Model
		Page(ctx context.Context, model *gdb.Model) *gdb.Model
		OrderBy(ctx context.Context, model *gdb.Model, tablePrefix ...string) *gdb.Model
		WhereBeginTime(ctx context.Context, columName string, model *gdb.Model, tablePrefix ...string) *gdb.Model
		WhereEndTime(ctx context.Context, columName string, model *gdb.Model, tablePrefix ...string) *gdb.Model
		GetSearchParams(ctx context.Context) *model.SearchParams
	}
)

var (
	localBizCtx IBizCtx
)

func BizCtx() IBizCtx {
	if localBizCtx == nil {
		panic("implement not found for interface IBizCtx, forgot register?")
	}
	return localBizCtx
}

func RegisterBizCtx(i IBizCtx) {
	localBizCtx = i
}
